Repository Arquisoft/dede_es4c, pull requests merged in 2022-03, with the labels that each got.

#61 uo277306 documentación vista despliegue
  docs/07_deployment_view.adoc
  docs/images/07_deployment_view.png
Labels: documentation, arreglo

#72 Pantalla signup
  webapp/src/App.css
  webapp/src/components/CartDrawer.tsx
  webapp/src/components/NavBar.tsx
  webapp/src/images/fondoComida.jpg
  webapp/src/pages/Home.tsx
  webapp/src/pages/Signup.tsx
  webapp/src/pages/styles/signup.css
Labels: Frontend

#74 Creada la pantalla de login
  webapp/package-lock.json
  webapp/package.json
  webapp/src/App.css
  webapp/src/App.tsx
  webapp/src/components/CartDrawer.tsx
  webapp/src/components/NavBar.tsx
  webapp/src/components/Producto.tsx
  webapp/src/components/styles/producto.css
  webapp/src/images/loginFondo.jpg
  webapp/src/images/user.png
  webapp/src/pages/Login.tsx
  webapp/src/pages/Signup.tsx
  webapp/src/pages/Tienda.tsx
  webapp/src/pages/styles/login.css
  webapp/src/pages/styles/signup.css
Labels: Frontend

#78 Listado productos
  restapi/package-lock.json
  webapp/src/App.css
  webapp/src/components/ClasePaginacion.tsx
  webapp/src/components/Paginacion.tsx
  webapp/src/images/pincho.png
  webapp/src/pages/Product.tsx
  webapp/src/pages/Producto.tsx
  webapp/src/pages/Productos.tsx
  webapp/src/pages/Tienda.tsx
Labels: Frontend

#109 Arreglado el área del botón del carrito
  webapp/src/components/CartDrawer.tsx
  webapp/src/components/NavBar.tsx
Labels: arreglo
